// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdyalejsbargjidfdtim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkeWFsZWpzYmFyZ2ppZGZkdGltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODE5MjEsImV4cCI6MjA3MTQ1NzkyMX0.1J1qDQL0D0PWOPuW2LqTtvx3xWZizPN902k_sjNm0Kw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});